#ifndef ARTICLE_PRICE_GLOBAL_H
#define ARTICLE_PRICE_GLOBAL_H
/*
#include <QtCore/qglobal.h>

#if defined(ARTICLE_PRICE_LIBRARY)
#  define ARTICLE_PRICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ARTICLE_PRICESHARED_EXPORT Q_DECL_IMPORT
#endif
*/
#endif // ARTICLE_PRICE_GLOBAL_H
